.PHONY: build test clean docker run deploy preconfig

BINARY=maxwell-irc
VERSION=$(shell git describe --tags --always --dirty 2>/dev/null || echo "dev")
GO ?= $(HOME)/go-install/go/bin/go
# Static binaries: the SQLite driver is pure Go, so cgo is never needed.
export CGO_ENABLED = 0

# Deployment profile — matches the directory .<PROFILE>/ created by `make preconfig`
PROFILE ?= maxwell
PROFILE_DIR = .$(PROFILE)
-include $(PROFILE_DIR)/settings.mk

# Fallback values used when no profile exists (or overridden on the command line)
PI_HOST     ?= maxwell.local
PI_USER     ?= maxwell
INSTALL_DIR ?= /opt/xirc

build:
	$(GO) build -ldflags="-s -w -X main.version=$(VERSION)" -o $(BINARY) .

test:
	$(GO) test ./...

test-verbose:
	$(GO) test -v ./...

# Cross-compile for Raspberry Pi 4 (ARM64)
build-pi:
	GOOS=linux GOARCH=arm64 $(GO) build -ldflags="-s -w -X main.version=$(VERSION)" -o $(BINARY)-arm64 .

# Cross-compile for Raspberry Pi 3 (ARM)
build-pi3:
	GOOS=linux GOARCH=arm GOARM=7 $(GO) build -ldflags="-s -w -X main.version=$(VERSION)" -o $(BINARY)-arm .

docker:
	docker build -f deploy/Dockerfile --build-arg VERSION=$(VERSION) -t xirc .

docker-up:
	cd deploy && docker compose up -d

docker-up-mariadb:
	cd deploy && docker compose --profile mariadb up -d

docker-down:
	cd deploy && docker compose down

run: build
	./$(BINARY) --config config.yaml

preconfig:
	@PROFILE=$(PROFILE) bash scripts/preconfig.sh

# Deploy to the target Pi.
# Reads PI_HOST, PI_USER, INSTALL_DIR from .$(PROFILE)/settings.mk (generated by preconfig).
# Override any variable on the command line, e.g.: make deploy PROFILE=maxwell PI_HOST=10.0.0.5
# The profile's config.yaml is only pushed when the target has none (the UI
# owns it after that); FORCE_CONFIG=1 pushes it anyway. PI_CONFIG always pushes.
PI_CONFIG ?=
FORCE_CONFIG ?=

deploy: build-pi
	@test -d "$(PROFILE_DIR)" || \
	  { echo "Error: profile '$(PROFILE)' not found. Run 'make preconfig PROFILE=$(PROFILE)' first."; exit 1; }
	rsync -avz --progress $(BINARY)-arm64 "$(PI_USER)@$(PI_HOST)":$(INSTALL_DIR)/xirc
	rsync -avz --delete web/ "$(PI_USER)@$(PI_HOST)":$(INSTALL_DIR)/web/
	rsync -avz $(PROFILE_DIR)/xirc.service "$(PI_USER)@$(PI_HOST)":/tmp/
	ssh "$(PI_USER)@$(PI_HOST)" "sudo cp /tmp/xirc.service /etc/systemd/system/xirc.service && sudo systemctl daemon-reload"
	@for f in nginx-xirc.conf nginx-xirc-location.conf apache-xirc.conf apache-xirc-location.conf; do \
	  [ -f "$(PROFILE_DIR)/$$f" ] || continue; \
	  rsync -avz "$(PROFILE_DIR)/$$f" "$(PI_USER)@$(PI_HOST)":/tmp/; \
	  case $$f in \
	    nginx-xirc.conf) ssh "$(PI_USER)@$(PI_HOST)" "sudo cp /tmp/$$f /etc/nginx/sites-available/xirc && sudo ln -sf /etc/nginx/sites-available/xirc /etc/nginx/sites-enabled/xirc && sudo nginx -t && sudo systemctl reload nginx" ;; \
	    nginx-xirc-location.conf) ssh "$(PI_USER)@$(PI_HOST)" "sudo cp /tmp/$$f /etc/nginx/snippets/xirc.conf && sudo nginx -t && sudo systemctl reload nginx" ;; \
	    apache-xirc.conf) ssh "$(PI_USER)@$(PI_HOST)" "sudo a2enmod -q proxy proxy_http proxy_wstunnel rewrite headers && sudo cp /tmp/$$f /etc/apache2/sites-available/xirc.conf && sudo a2ensite -q xirc && sudo apachectl configtest && sudo systemctl reload apache2" ;; \
	    apache-xirc-location.conf) ssh "$(PI_USER)@$(PI_HOST)" "sudo a2enmod -q proxy proxy_http proxy_wstunnel rewrite headers && sudo cp /tmp/$$f /etc/apache2/conf-available/xirc.conf && sudo apachectl configtest && sudo systemctl reload apache2" ;; \
	  esac; \
	done
	@if [ -n "$(PI_CONFIG)" ]; then \
	  rsync -avz --progress "$(PI_CONFIG)" "$(PI_USER)@$(PI_HOST)":$(INSTALL_DIR)/config.yaml; \
	elif [ -f "$(PROFILE_DIR)/config.yaml" ]; then \
	  rsync -avz --progress $(if $(filter 1,$(FORCE_CONFIG)),,--ignore-existing) "$(PROFILE_DIR)/config.yaml" "$(PI_USER)@$(PI_HOST)":$(INSTALL_DIR)/config.yaml; \
	fi
	ssh "$(PI_USER)@$(PI_HOST)" "sudo systemctl restart xirc"

clean:
	rm -f $(BINARY) $(BINARY)-arm64 $(BINARY)-arm
