#!/usr/bin/env bash
# maXwell IRC deployment preconfig — generates a named profile directory with all
# deployment artefacts: config.yaml, xirc.service, reverse-proxy config, settings.mk.
# Run with: bash scripts/preconfig.sh   or   make preconfig [PROFILE=name]
set -euo pipefail

source "$(dirname "$0")/proxy-templates.sh"

# ── helpers ───────────────────────────────────────────────────────────────────

ask() {
    local prompt="$1" default="$2" var_name="$3"
    local input
    printf '%s [%s]: ' "$prompt" "$default" >&2
    read -r input
    printf -v "$var_name" '%s' "${input:-$default}"
}

ask_yn() {
    local prompt="$1" default="$2" var_name="$3"
    local input
    while true; do
        printf '%s [%s]: ' "$prompt" "$default" >&2
        read -r input
        input="${input:-$default}"
        case "${input,,}" in
            y|yes) printf -v "$var_name" 'y'; return ;;
            n|no)  printf -v "$var_name" 'n'; return ;;
            *)     echo "  Please enter y or n." >&2 ;;
        esac
    done
}

hr() { echo "  ──────────────────────────────────────────────────────────"; }

# ── welcome ───────────────────────────────────────────────────────────────────

echo
echo "  maXwell IRC deployment preconfig"
hr
echo "  Press Enter to accept the default shown in [brackets]."
echo

# ── profile name ─────────────────────────────────────────────────────────────

ask "Target server name (profile name)" "${PROFILE:-maxwell}" PROFILE
PROFILE_DIR=".${PROFILE}"

if [[ -d "$PROFILE_DIR" ]]; then
    echo
    echo "  Note: ${PROFILE_DIR}/ already exists — files will be overwritten."
fi

# ── deployment target ─────────────────────────────────────────────────────────

echo
echo "  -- Deployment target --"
ask "SSH host (IP or hostname of the Pi)" "maxwell.local" PI_HOST
ask "SSH user (must have passwordless sudo)" "maxwell" PI_USER

# ── installation ──────────────────────────────────────────────────────────────

echo
echo "  -- Installation --"
ask "Install directory on target" "/opt/xirc" INSTALL_DIR
ask "Service OS username" "xirc" XIRC_USER
ask "HTTP port maxwell-irc listens on" "8085" XIRC_PORT

# ── storage ───────────────────────────────────────────────────────────────────

echo
echo "  -- Storage directories (paths on the target server) --"
ask "Downloads directory" "/srv/downloads" DOWNLOADS_DIR
ask "DLNA / media directory" "/srv/dlna/media" MEDIA_DIR
ask "Temp directory (for in-progress DCC transfers)" "${DOWNLOADS_DIR}/.tmp" TEMP_DIR

# ── database ──────────────────────────────────────────────────────────────────

echo
echo "  -- Database --"
echo "  maXwell IRC creates all tables automatically on first startup (CREATE TABLE IF NOT EXISTS)."
echo "  No manual schema setup is required."
echo
echo "  Options: sqlite  mysql"
ask "Database driver" "sqlite" DB_DRIVER

case "${DB_DRIVER,,}" in
    sqlite)
        DB_DRIVER="sqlite"
        ask "SQLite file path (on target)" "${INSTALL_DIR}/data/xirc.db" DB_PATH
        DB_DSN=""
        ;;
    mysql|mariadb)
        DB_DRIVER="mysql"
        DB_PATH=""
        echo
        echo "  DSN format: user:password@tcp(host:3306)/dbname"
        echo "  The database and user must already exist; tables are created automatically."
        ask "MySQL DSN" "mxirc:changeme@tcp(127.0.0.1:3306)/maxwell_irc" DB_DSN
        ;;
    *)
        echo "  Unknown driver '${DB_DRIVER}' — defaulting to sqlite."
        DB_DRIVER="sqlite"
        ask "SQLite file path (on target)" "${INSTALL_DIR}/data/xirc.db" DB_PATH
        DB_DSN=""
        ;;
esac

# ── reverse proxy + login ────────────────────────────────────────────────────

echo
echo "  -- Reverse proxy --"
ask "Reverse proxy (nginx / apache / none)" "nginx" PROXY
PROXY="${PROXY,,}"
PROXY_MODE=""; PROXY_PREFIX=""; PROXY_SERVER_NAME=""
if [[ "$PROXY" == "nginx" || "$PROXY" == "apache" ]]; then
    echo "    s) Own site   — new ${PROXY} site with its own hostname"
    echo "    i) Subpath    — snippet to include in an existing site"
    ask "Mode" "i" PROXY_MODE
    if [[ "${PROXY_MODE,,}" == s* ]]; then
        PROXY_MODE="site"
        ask "Hostname for the site" "xirc.local" PROXY_SERVER_NAME
    else
        PROXY_MODE="subpath"
        ask "URL prefix (no trailing slash)" "/xirc" PROXY_PREFIX
    fi
else
    PROXY="none"
    echo "  Without a proxy, put xirc behind TLS before exposing it to the internet."
fi

echo
echo "  -- Login --"
ask "Networks that skip login (comma-separated CIDRs, empty = always log in)" "" TRUSTED_NETWORKS
ask "Role for those networks (admin / user)" "admin" TRUSTED_ROLE

# ── generate files ────────────────────────────────────────────────────────────

mkdir -p "$PROFILE_DIR"

# --- settings.mk (read by Makefile) ---
cat > "${PROFILE_DIR}/settings.mk" <<SETTINGS
# Generated by scripts/preconfig.sh — do not edit by hand; re-run preconfig.
PI_HOST     := ${PI_HOST}
PI_USER     := ${PI_USER}
INSTALL_DIR := ${INSTALL_DIR}
XIRC_USER   := ${XIRC_USER}
SETTINGS

# --- config.yaml ---
if [[ "$DB_DRIVER" == "sqlite" ]]; then
    DB_BLOCK="database:
  driver: sqlite
  path: ${DB_PATH}"
else
    DB_BLOCK="database:
  driver: mysql
  dsn: \"${DB_DSN}\""
fi

PREFIX_LINE=""
[[ -n "$PROXY_PREFIX" ]] && PREFIX_LINE="  prefix: ${PROXY_PREFIX}"

cat > "${PROFILE_DIR}/config.yaml" <<CONFIG
server:
  host: 127.0.0.1
  port: ${XIRC_PORT}
${PREFIX_LINE}

${DB_BLOCK}

storage:
  media_dir: ${MEDIA_DIR}
  downloads_dir: ${DOWNLOADS_DIR}
  temp_dir: ${TEMP_DIR}
  min_free_space: 1GB

downloads:
  max_concurrent: 3

auth:
  trusted_networks: [${TRUSTED_NETWORKS}]
  trusted_role: ${TRUSTED_ROLE}
CONFIG

# --- xirc.service ---
cat > "${PROFILE_DIR}/xirc.service" <<SERVICE
[Unit]
Description=maXwell IRC - XDCC IRC Web Client
After=network.target
Wants=network-online.target

[Service]
Type=simple
User=${XIRC_USER}
Group=${XIRC_USER}
WorkingDirectory=${INSTALL_DIR}
ExecStart=${INSTALL_DIR}/xirc --config ${INSTALL_DIR}/config.yaml
Restart=always
RestartSec=5
StartLimitIntervalSec=120
StartLimitBurst=5
RestartPreventExitStatus=78
StandardOutput=journal
StandardError=journal

# NoNewPrivileges is universally supported; the namespace-based options
# (ProtectSystem=strict, ProtectHome, PrivateTmp) are omitted because
# they require mount namespaces which may not be available on all kernels.
NoNewPrivileges=yes
# Group-writable files/dirs so the shared media group (and other users in
# it) can keep managing what xirc downloads and creates.
UMask=0002

[Install]
WantedBy=multi-user.target
SERVICE

# --- reverse-proxy config (via scripts/proxy-templates.sh renderers) ---
rm -f "${PROFILE_DIR}"/nginx-*.conf "${PROFILE_DIR}"/apache-*.conf "${PROFILE_DIR}/.no-nginx"
if [[ "$PROXY" != "none" ]]; then
    suffix=""; [[ "$PROXY_MODE" == "subpath" ]] && suffix="-location"
    PORT="$XIRC_PORT" PREFIX="$PROXY_PREFIX" SERVER_NAME="$PROXY_SERVER_NAME" \
        "render_${PROXY}_${PROXY_MODE}" > "${PROFILE_DIR}/${PROXY}-xirc${suffix}.conf"
fi

# --- .gitignore ---
GITIGNORE=".gitignore"
GI_PATTERN=".${PROFILE}/"
if ! grep -qxF "$GI_PATTERN" "$GITIGNORE" 2>/dev/null; then
    echo "$GI_PATTERN" >> "$GITIGNORE"
    echo "  Added '${GI_PATTERN}' to .gitignore"
fi

# ── summary ───────────────────────────────────────────────────────────────────

echo
hr
echo "  Generated: ${PROFILE_DIR}/"
echo "    config.yaml       application config"
echo "    xirc.service      systemd unit"
if [[ "$PROXY" != "none" ]]; then
    suffix=""; [[ "$PROXY_MODE" == "subpath" ]] && suffix="-location"
    echo "    ${PROXY}-xirc${suffix}.conf   ${PROXY} $( [[ "$PROXY_MODE" == "site" ]] && echo "site config" || echo "snippet (include in your existing site)" )"
fi
echo "    settings.mk       Makefile deploy variables"
hr
echo
echo "  First deploy (pushes config + binary + service files):"
echo "    make deploy PROFILE=${PROFILE}"
echo
echo "  For first-time Pi setup, follow: docs/install.md"
echo
